language: python
sudo: required
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - SALT_PILLARROOT=$TRAVIS_BUILD_DIR/tests/pillar/test-linux-main
    - SALT_REPO_URL=https://archive.repo.saltstack.com/yum/redhat/7/x86_64/2019.2.repo
  matrix:
    - OS_VERSION=7 SALT_STATE=ash-linux.stig
    - OS_VERSION=7 SALT_STATE=ash-linux.iavm
    - OS_VERSION=7 SALT_STATE=ash-linux.scap
    - OS_VERSION=7 SALT_STATE=ash-linux.vendor
    - OS_VERSION=7 SALT_STATE=ash-linux.el7.stig
    - OS_VERSION=7 SALT_STATE=ash-linux.el7.STIGbyID.cat1
    - OS_VERSION=7 SALT_STATE=ash-linux.el7.STIGbyID.cat2
    - OS_VERSION=7 SALT_STATE=ash-linux.el7.STIGbyID.cat3

services:
  - docker

before_install:
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' |
      sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - sudo docker build -t local/centos:${OS_VERSION} tests/docker/centos${OS_VERSION}

install:
  - sudo docker run --detach --privileged
      --volume="${TRAVIS_BUILD_DIR}":"${TRAVIS_BUILD_DIR}":ro
      --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro
      --name centos-${OS_VERSION} local/centos:${OS_VERSION} init
  - sudo docker exec centos-${OS_VERSION} touch /etc/fstab
  - sudo docker exec centos-${OS_VERSION} curl -sSL -o /etc/yum.repos.d/salt.repo ${SALT_REPO_URL}
  - sudo docker exec centos-${OS_VERSION} yum -y install
      $(<${TRAVIS_BUILD_DIR}/tests/requirements.txt)
      $(<${TRAVIS_BUILD_DIR}/tests/requirements-el${OS_VERSION}.txt)
  - sudo docker exec centos-${OS_VERSION} salt-call --versions-report
  - sudo docker exec centos-${OS_VERSION} salt-call --local
      --retcode-passthrough
      --file-root=$TRAVIS_BUILD_DIR
      --pillar-root=$SALT_PILLARROOT
      saltutil.sync_all

script:
  - sudo docker exec centos-${OS_VERSION} salt-call --local
      --retcode-passthrough --log-file-level debug
      --file-root=$TRAVIS_BUILD_DIR
      --pillar-root=$SALT_PILLARROOT
      state.show_sls
      $SALT_STATE
  - sudo docker exec centos-${OS_VERSION} salt-call --local
      --retcode-passthrough --log-file-level debug
      --file-root=$TRAVIS_BUILD_DIR
      --pillar-root=$SALT_PILLARROOT
      state.sls
      $SALT_STATE
      mock=True

after_failure:
  - sudo docker exec centos-${OS_VERSION} salt-call --local grains.items
  - sudo docker exec centos-${OS_VERSION} sh -c set
  - sudo docker exec centos-${OS_VERSION} more /var/log/salt/* | cat

after_script:
  - sudo docker stop centos-${OS_VERSION}

notifications:
  email:
    on_success: never
    on_failure: always
